services:
  - type: web
    name: mikasa-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m tg_bot
    runtime: python-3.10.13
    envVars:
      - key: TOKEN
        sync: false
